"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import Sidebar from "../components/sidebar";
import Header from "../components/header";
import { Box, Flex } from "@chakra-ui/react";
import { useReportWebVitals } from "next/web-vitals";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Rotate FE Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useReportWebVitals((metric) => {
    console.log(metric);
  });
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <Flex justifyContent={"space-between"} width={"100vw"}>
            <Sidebar />

            <Flex
              width={"100%"}
              flex={1}
              justifyContent={"flex-end"}
              alignItems={"flex-end"}
              flexDirection={"column"}
            >
              <Header />
              <Box w="80%" alignSelf={"flex-end"} mt="90px">
                {children}
              </Box>
            </Flex>
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
